spring:
  application:
    name: serve-8001

server:
  port: 8001
  # for test using, limit the thread pool for whole server
  tomcat:
    threads:
      max: 5

logging:
  pattern:
    console: "%date{yy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} --- [%15.15t] %-40.40logger{39}[%4line]: %msg%n"
  level:
    org.springframework.web: DEBUG